#!/usr/bin/env python3
"""Generate discovery.yml from the front-matter of every tracked file.

Never edit discovery.yml by hand. This script owns it, and CI runs it on
every push to main. A hand-maintained index is wrong within a week, and a
wrong index is worse than no index because agents trust it.
"""
from __future__ import annotations

import datetime as _dt
import pathlib
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from pdlib import as_date, changed_at, parse_review, reconciled_at, repo_root, superseded_by, walk  # noqa: E402

PROTOTYPE = "prototype"


def build(root: pathlib.Path) -> dict:
    deliverables: dict[str, dict] = {}
    material: list[dict] = []
    calls = 0
    rules: list[dict] = []

    replaced = superseded_by(root)
    for path, fm in walk(root):
        rel = str(path.relative_to(root))
        kind = fm.get("kind")
        changed = changed_at(fm, path, root)
        reconciled = reconciled_at(fm, path, root)

        if fm.get("deliverable"):
            entry = {
                "id": fm["deliverable"],
                "path": rel,
                "project_number": fm.get("project_number"),
                "status": fm.get("status", "draft"),
                "owner": fm.get("owner"),
                "updated": fm.get("updated"),
                "changed": changed.isoformat() if changed else None,
                "reconciled": reconciled.isoformat() if reconciled else None,
                "confirmed_with_client": fm.get("confirmed_with_client"),
                "depends_on": fm.get("depends_on", []),
                "feeds": fm.get("feeds", []),
                "decisions": fm.get("decisions", []),
                "superseded_citations": [
                    {"cites": d, "replaced_by": replaced[d]} for d in (fm.get("decisions") or []) if d in replaced
                ],
                "reviewed": [
                    {"id": k, "date": (d.isoformat() if d else None), "reason": r}
                    for k, v in (fm.get("reviewed") or {}).items() if isinstance(fm.get("reviewed"), dict)
                    for d, r in [parse_review(v)]
                ],
            }
            if fm.get("figma"):
                entry["figma"] = fm["figma"]
                entry["figma_checked"] = fm.get("figma_checked")
            deliverables[entry["id"]] = entry
        elif kind == "material":
            material.append({
                "path": rel,
                "topic": fm.get("topic"),
                "status": fm.get("status", "raw"),
                "added": fm.get("added"),
                "added_by": fm.get("added_by"),
                "source": fm.get("source"),
                "feeds": fm.get("feeds", []),
            })
        elif kind == "call":
            calls += 1
        elif kind == "rules":
            rules.append({
                "path": rel,
                "feature": fm.get("feature"),
                "status": fm.get("status", "draft"),
                "covers": fm.get("covers", []),
                "changed": changed.isoformat() if changed else None,
                "reconciled": reconciled.isoformat() if reconciled else None,
            })

    # Staleness. A deliverable is stale when anything it depends on changed later.
    for entry in deliverables.values():
        mine = as_date(entry["reconciled"])
        reviewed = {r["id"]: as_date(r["date"]) for r in entry["reviewed"]}
        stale = []
        for dep_id in entry["depends_on"]:
            dep = deliverables.get(dep_id)
            if not dep:
                continue
            theirs = as_date(dep["changed"])
            if mine and theirs and theirs > mine:
                seen = reviewed.get(dep_id)
                if seen and seen >= theirs:
                    continue  # reviewed after the change, and judged still correct
                stale.append({"id": dep_id, "changed": dep["changed"]})
        entry["stale_upstream"] = stale
        if entry.get("figma"):
            checked, changed_d = as_date(entry.get("figma_checked")), as_date(entry["changed"])
            entry["figma_behind"] = bool(checked and changed_d and checked < changed_d)

    # The prototype is downstream of everything that names it in `feeds`.
    proto = deliverables.get("10-development-ready-prototype")
    proto_inputs = sorted(proto["depends_on"]) if proto else sorted(
        d["id"] for d in deliverables.values() if PROTOTYPE in d["feeds"])

    return {
        "note": "Generated by scripts/build_index.py. Never edit by hand. Regenerate before every pull request; the validate check fails when it is stale.",
        "counts": {
            "deliverables": len(deliverables),
            "confirmed": sum(1 for d in deliverables.values() if d["status"] == "confirmed"),
            "stale": sum(1 for d in deliverables.values() if d["stale_upstream"]),
            "superseded_citations": sum(len(d["superseded_citations"]) for d in deliverables.values()),
            "calls": calls,
            "material_raw": sum(1 for m in material if m["status"] == "raw"),
        },
        "deliverables": [deliverables[k] for k in sorted(deliverables)],
        "prototype": {"inputs": proto_inputs, "rules_pages": rules},
        "material": sorted(material, key=lambda m: m["path"]),
    }


def main() -> int:
    root = repo_root()
    index = build(root)
    out = root / "discovery.yml"
    out.write_text(
        yaml.safe_dump(index, sort_keys=False, allow_unicode=True, default_flow_style=False),
        encoding="utf-8",
    )
    c = index["counts"]
    print(f"discovery.yml: {c['deliverables']} deliverables, "
          f"{c['confirmed']} confirmed, {c['stale']} stale, {c['superseded_citations']} superseded citation(s), "
          f"{c['material_raw']} raw material")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
